In [18]:
import torch
device='cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [4]:
with open('wizard_of_oz.txt','r',encoding='utf-8') as file:
    text=file.read()
print(text[:200])

# print(text) // to print the whole text

The Project Gutenberg eBook of Dorothy and the Wizard in Oz
    
This ebook is for the use of anyone anywhere in the United States and
most other parts of the world at no cost and with almost no rest


In [5]:
chars=set(sorted(text))
print(chars)
print(len(chars))

{'K', '*', ' ', 'l', 'P', 'c', '\ufeff', 'u', 'x', ')', '[', 't', 'G', '!', 'L', 'Z', '6', 'i', '4', '"', '7', 'q', 'H', ']', 'S', '5', 'U', 'A', 'g', 'R', '-', 'd', 'w', 'I', ',', '0', 'b', 'j', 'X', '\n', 'r', 'e', '/', 'B', 'a', 'n', 'E', 'Q', 'p', 'k', '(', ';', 'D', '?', 'N', 'y', '8', 'C', ':', '#', '.', '_', '1', '2', 's', 'T', '9', '&', 'h', 'F', 'Y', 'o', 'm', 'W', 'z', "'", 'v', 'V', 'J', 'M', '3', 'O', 'f'}
83


In [6]:
string_to_int = {ch: i for i, ch in enumerate(chars)}
int_to_string = {i: ch for i, ch in enumerate(chars)}
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

print(encode('hello'))

encoded_hello=encode('hello')
decoded_hello=decode(encoded_hello)
print(decoded_hello)

[68, 41, 3, 3, 71]
hello


In [7]:
import torch

string_to_int = {ch: i for i, ch in enumerate(chars)}
int_to_string = {i: ch for i, ch in enumerate(chars)}
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

data = torch.tensor(encode(text),dtype =torch.long)
print(data[:100])

tensor([ 6, 65, 68, 41,  2,  4, 40, 71, 37, 41,  5, 11,  2, 12,  7, 11, 41, 45,
        36, 41, 40, 28,  2, 41, 43, 71, 71, 49,  2, 71, 82,  2, 52, 71, 40, 71,
        11, 68, 55,  2, 44, 45, 31,  2, 11, 68, 41,  2, 73, 17, 74, 44, 40, 31,
         2, 17, 45,  2, 81, 74, 39,  2,  2,  2,  2, 39, 65, 68, 17, 64,  2, 41,
        36, 71, 71, 49,  2, 17, 64,  2, 82, 71, 40,  2, 11, 68, 41,  2,  7, 64,
        41,  2, 71, 82,  2, 44, 45, 55, 71, 45])


In [13]:
n=int(0.8*len(data))
train_data=data[:n]
val_data=data[n:]

print(train_data.shape,val_data.shape)

print(train_data)

print(val_data)

torch.Size([186743]) torch.Size([46686])
tensor([ 6, 65, 68,  ...,  2, 69, 17])
tensor([40, 64, 11,  ..., 45, 31, 39])


In [17]:
block_size  = 8
x = train_data[:block_size]
y = train_data[1:block_size+1]

for t in range(block_size):
    context=x[ :t+1]
    target=y[t]
    print("when input is ",context,"target is ",target)

when input is  tensor([6]) target is  tensor(65)
when input is  tensor([ 6, 65]) target is  tensor(68)
when input is  tensor([ 6, 65, 68]) target is  tensor(41)
when input is  tensor([ 6, 65, 68, 41]) target is  tensor(2)
when input is  tensor([ 6, 65, 68, 41,  2]) target is  tensor(4)
when input is  tensor([ 6, 65, 68, 41,  2,  4]) target is  tensor(40)
when input is  tensor([ 6, 65, 68, 41,  2,  4, 40]) target is  tensor(71)
when input is  tensor([ 6, 65, 68, 41,  2,  4, 40, 71]) target is  tensor(37)
