In [1]:
import torch

In [2]:
randint=torch.randint(-20,20,(5,))
randint

tensor([-14,  -4,  -1, -19, -14])

In [3]:
tensor=torch.tensor([[0.1,1.2,2.2],[2.1,3.2,4.1]])
tensor

tensor([[0.1000, 1.2000, 2.2000],
        [2.1000, 3.2000, 4.1000]])

In [4]:
zeros=torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
ones=torch.ones(2,3)
ones

In [ ]:
range= torch.range(6)
range

In [ ]:
linspace=torch.linspace